language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: tonkworks
  password:
    secure: W65PmQu4z11/Gy3bNWsqxX59Itl/hikERLjtqjIMa/3QIRRJs7A18N4PWDX+OE5cy28zmbBKCyrFr3KLnMuYUlHhEaqUYiEb55Z/06zK+UE3fI9UjcBbamK7efr0H3DlwzJGdkBn5Rjl+G4wn6gBI6DNP3hh5DAojl7MGkR65b4AGSsV9VH+npocAVAEdBl1Q5UmOKNSX9b3SJATZ40pY9BgxIzz7UCjtlvi7+b6FUM6qsjSan+wGdGiVA57LRVXZrCLJB2Zf/8bIoZdoNZMiDXsy7lRIZ/j6xuFkRIR0FF5PgqMt9XTQ875l57yHbcHQ52Z7gDvwB+CnjMbYRcsHIGQJowqjzLf36F1y/UsE5Ery7fW90swMVktkrxiWjF1MadTKRvHpUa+lTja70Zu5rALv6vHnMNq2OpwsqtcYVC+omDxv/Y3QeYDYirfOVDZjWoD29tBA9HZzU3FpldQGF1mkrahtVvekH2wkmXhsc4uaeho/dRc/fPF3KMXKWFn7l9o5P+vD4WUKiJERKHvw4OkBKKmp+5GTNIhoteAB5/zrd/SW/aEZUh2KnkECUMW+jxDE/OO/FhVYo0PF+B45LgUHjjOdhArzp2dEwch6gTMUwy92zvdw8afjsVw3LDKV7MwyamlxsKv4YnTj6dxk/TI0/VMx8yFuUev1lzqILk=
  on:
    tags: true
    repo: tonkworks/r2ds_api
    python: 3.6
